name: mlflow-env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip

  - pip:
      - mlflow==2.19.0
      - pandas==2.2.3
      - scikit-learn==1.5.2
      - numpy==2.0.2
      - cloudpickle==3.1.0
      - psutil==6.1.1
      - scipy==1.14.1
      - matplotlib==3.10.0
      - seaborn==0.13.2
      - imbalanced-learn==0.12.4
      - dagshub==0.5.9