name: MLflow CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:

      # =========================
      # CHECKOUT
      # =========================
      - name: Checkout Repository
        uses: actions/checkout@v4

      # =========================
      # SETUP PYTHON
      # =========================
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # =========================
      # INSTALL DEPENDENCIES
      # =========================
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0
          pip install -r MLProject/requirements.txt

      # =========================
      # RUN MLFLOW PROJECT
      # =========================
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local

      # =========================
      # UPLOAD MODEL ARTIFACT
      # =========================
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: telco-churn-model-artifact
          path: MLProject/artifacts/model

      # =========================
      # LOGIN DOCKER HUB
      # =========================
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # =========================
      # BUILD DOCKER IMAGE FROM MLFLOW MODEL
      # =========================
      - name: Build Docker Image
        shell: bash
        run: |
          mlflow models build-docker \
            --model-uri MLProject/artifacts/model \
            --name telco-churn-model \
            --env-manager local

      # =========================
      # TAG IMAGE
      # =========================
      - name: Tag Docker Image
        shell: bash
        run: |
          docker tag telco-churn-model \
            ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest

      # =========================
      # PUSH IMAGE
      # =========================
      - name: Push Docker Image
        shell: bash
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest
